### ISSUE TITLE
java and spring boot support

### ISSUE THREAD

**Issue by AnnaKayam** [hdisysteme/MongoBumblebee#48]
does mongoBumblebee supports java 8 and spring boot 2.0.4?
what is the minimal java and spring-boot versions support?

**Comment by blafoo** [comment]
Hi, MongoBumblebee itself does not require Spring Boot. With small changes Java 8 would be sufficent. BUT:

"The Spring Data MongoDB 4.x binaries require JDK level 17 and above and [Spring Framework](https://spring.io/docs) 6.1.5 and above." See https://docs.spring.io/spring-data/mongodb/reference/preface.html
